spring.application.name=inventory-system
server.port=8080

# --- CONFIGURACIÓN DE JWT (SUPABASE) ---
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://hrblmsycgjyzujbxwjtm.supabase.co/auth/v1/.well-known/jwks.json?apiKey=sb_publishable_IkDMONh_dvHXs4yvOMyZYQ_xiQs57vN
# Esta es la línea mágica que le dice a Spring que acepte ES256
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256

# --- CONEXIÓN A BASE DE DATOS SUPABASE ---
spring.datasource.url=jdbc:postgresql://db.hrblmsycgjyzujbxwjtm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=g?DyTtRX5n@ahQ=
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACIÓN DE HIBERNATE (JPA) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- CONFIGURACIÓN DE SUPABASE STORAGE ---
# Usamos el ID de tu proyecto que ya hemos visto en tus configuraciones anteriores
supabase.url=https://hrblmsycgjyzujbxwjtm.supabase.co
# Pega aquí exactamente la misma llave 'anon public' que usaste en la URL del jwks
supabase.key=sb_publishable_IkDMONh_dvHXs4yvOMyZYQ_xiQs57vN
supabase.bucket.name=inventory
supabase.bucket.folder=receipts