spring.application.name=inventory-system
server.port=8080

# --- JWT CONFIGURATION (SUPABASE) ---
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://hrblmsycgjyzujbxwjtm.supabase.co/auth/v1/.well-known/jwks.json?apiKey=sb_publishable_IkDMONh_dvHXs4yvOMyZYQ_xiQs57vN
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256

# --- SUPABASE DATABASE CONNECTION ---
spring.datasource.url=jdbc:postgresql://db.hrblmsycgjyzujbxwjtm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=g?DyTtRX5n@ahQ=
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate (JPA) Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- SUPABASE STORAGE CONFIGURATION ---
supabase.url=https://hrblmsycgjyzujbxwjtm.supabase.co
supabase.key=sb_publishable_IkDMONh_dvHXs4yvOMyZYQ_xiQs57vN
supabase.bucket.name=inventory
supabase.bucket.folder=receipts