spring.application.name=inventory-system
server.port=8080

# --- JWT CONFIGURATION (SUPABASE) ---
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://hrblmsycgjyzujbxwjtm.supabase.co/auth/v1/.well-known/jwks.json?apiKey=${SUPABASE_KEY}
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256

# --- SUPABASE DATABASE CONNECTION ---
#jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.hrblmsycgjyzujbxwjtm&password=[YOUR-PASSWORD]
#jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?user=postgres.hrblmsycgjyzujbxwjtm&password=[YOUR-PASSWORD]
#spring.datasource.url=jdbc:postgresql://db.hrblmsycgjyzujbxwjtm.supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?user=postgres.hrblmsycgjyzujbxwjtm
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate (JPA) Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- SUPABASE STORAGE CONFIGURATION ---
supabase.url=https://hrblmsycgjyzujbxwjtm.supabase.co
supabase.key=${SUPABASE_KEY}
supabase.bucket.name=inventory
supabase.bucket.folder=receipts