name: Deploy Backend to OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Create a .env file securely
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env

      - name: 3. Copy files to the OCI server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY }}
          source: "."
          target: "~/spring-erp-backend"

      - name: 4. Start Docker on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd ~/spring-erp-backend
            
            sudo docker compose up -d --build
            
            sudo docker image prune -f